#   Copyright 2020 The Silkworm Authors
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

image: Visual Studio 2019
platform: x64
configuration: Release

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

install:
  - cd c:\Tools\vcpkg
  - vcpkg install mpir:x64-windows

cache:
  - C:\Tools\vcpkg\installed -> .appveyor.yml
  - C:\.hunter -> .appveyor.yml, cmake\toolchain.cmake, cmake\Hunter\config.cmake, cmake\Hunter\core_packages.cmake, cmake\Hunter\extra_packages.cmake

before_build:
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - git submodule sync
  - git submodule update --init --recursive
  - SET INCLUDE=C:\Tools\vcpkg\installed\x64-windows\include;%INCLUDE%
  - SET PATH=C:\Tools\vcpkg\installed\x64-windows\bin;%PATH%
  - cmake -H. -Bbuild -Wno-dev

build:
  project: build\silkworm.sln

test_script:
  - cd Build
  - cmd\Release\core_test.exe
  - cmd\Release\db_test.exe
  - cmd\Release\consensus.exe
